---
title: "ego_ignorance"
author: "S. Shin"
date: '2022-10-28'
output: html_document
---

# Load packages
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(tidyverse)
```

#Load and Wrangle Data
```{r}
sandbox_data <- read_csv("../../data/sandbox_trials.csv")

#add some info
sandbox_data <- sandbox_data %>% 
  mutate(
    response_alter_occluded = case_when(
      substring(alter_occluders, response+1, response+1) == '0' ~ TRUE,
      TRUE ~ FALSE
    ),
    response_ego_occluded = case_when(
      substring(ego_occluders, response+1, response+1) == '0' ~ TRUE,
      TRUE ~ FALSE
    )
  )

```

#Figures

##Proposed analysis from thesis
```{r}
#take cases when ego can see at least one position, and alter can see nothing
alter_ig_data <- sandbox_data %>% 
  filter(
    ego_occluders == '011' | ego_occluders != '110' | ego_occluders != '101',
    alter_occluders == '111'
  ) %>% 
  group_by(ego_ball_visible) %>% 
  count(response_ego_occluded) %>% 
  rename(responses = n)

fig1 <- ggplot(
  data = alter_ig_data,
  mapping = aes(
    x = ego_ball_visible,
    y = responses,
    fill = response_ego_occluded)
  ) +
  geom_col(
    position = 'dodge'
  )

fig1
```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
